In [2]:
from pathlib import Path

import pandas as pd

In [3]:
df_results = pd.DataFrame()
for i in range(40):
    path_results = f"{i}_results_gdsearch.json.gz"
    df_results = pd.concat(
        [df_results, pd.read_json(path_results, orient="index")], axis=0
    )
print(df_results.shape)
display(df_results.head())

(360000, 5)

,hparams,mae,rmse,spearman,r2_score
0,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",8.629867,16.609439,0.730443,0.621281
1,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",8.632387,16.715962,0.734235,0.616408
2,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",8.656920,16.751074,0.736201,0.614794
3,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",8.664890,16.739454,0.736134,0.615329
4,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",8.653915,16.705779,0.735826,0.616875

In [4]:
for metric, ascending in zip(
    ["mae", "rmse", "spearman", "r2_score"], [True, True, False, False]
):
    display(df_results.sort_values(by=metric, ascending=ascending).iloc[:5])

,hparams,mae,rmse,spearman,r2_score
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.967402,13.735773,0.788922,0.740992
270002,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.987224,13.774205,0.790009,0.739540
270004,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.007572,13.817482,0.789782,0.737901
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.018415,13.808971,0.786906,0.738224
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.027663,13.857734,0.787767,0.736372

,hparams,mae,rmse,spearman,r2_score
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.967402,13.735773,0.788922,0.740992
270002,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.987224,13.774205,0.790009,0.739540
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.018415,13.808971,0.786906,0.738224
270004,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.007572,13.817482,0.789782,0.737901
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.027663,13.857734,0.787767,0.736372

,hparams,mae,rmse,spearman,r2_score
270904,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",7.468237,15.048293,0.811410,0.689128
270922,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",7.468237,15.048293,0.811410,0.689128
270913,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",7.468237,15.048293,0.811410,0.689128
270920,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",7.441891,15.027954,0.811257,0.689968
270902,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",7.441891,15.027954,0.811257,0.689968

,hparams,mae,rmse,spearman,r2_score
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.967402,13.735773,0.788922,0.740992
270002,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.987224,13.774205,0.790009,0.739540
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.018415,13.808971,0.786906,0.738224
270004,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.007572,13.817482,0.789782,0.737901
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.027663,13.857734,0.787767,0.736372

In [5]:
index_opti = 270003
hparams_opti = df_results.loc[index_opti]["hparams"]
hparams_opti.pop("n_jobs")
hparams_opti

{'max_depth': 10,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 250,
 'random_state': 42}

In [6]:
path_hparams_opti = "hparams_opti.json"
df_hparams_opti = pd.DataFrame.from_dict(hparams_opti, orient="index")
if not Path(path_hparams_opti).exists():
    df_hparams_opti.to_json(path_hparams_opti)

pd.read_json(path_hparams_opti).to_dict()[0]

{'max_depth': 10.0,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 250.0,
 'random_state': 42.0}