In [2]:
from pathlib import Path

import pandas as pd

In [3]:
df_results = pd.DataFrame()
for i in range(40):
    path_results = f"{i}_results_gdsearch.json.gz"
    df_results = pd.concat(
        [df_results, pd.read_json(path_results, orient="index")], axis=0
    )
print(df_results.shape)
display(df_results.head())

(360000, 5)

,hparams,mae,rmse,spearman,r2_score
0,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.510852,19.117945,0.824118,0.560211
1,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.525459,19.144904,0.825050,0.558970
2,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.499845,19.131275,0.825481,0.559597
3,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.511455,19.140500,0.826172,0.559172
4,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.536421,19.184301,0.825923,0.557153

In [4]:
for metric, ascending in zip(
    ["mae", "rmse", "spearman", "r2_score"], [True, True, False, False]
):
    display(df_results.sort_values(by=metric, ascending=ascending).iloc[:5])

,hparams,mae,rmse,spearman,r2_score
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.783965,16.597884,0.868456,0.668512
270007,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.808299,16.625876,0.868535,0.667393
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.809545,16.622568,0.868298,0.667525
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.811799,16.666660,0.868249,0.665759
270002,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.816857,16.694772,0.866952,0.664631

,hparams,mae,rmse,spearman,r2_score
270010,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.829792,16.576679,0.866679,0.669359
270009,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.848839,16.577123,0.868501,0.669341
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.783965,16.597884,0.868456,0.668512
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.809545,16.622568,0.868298,0.667525
270007,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.808299,16.625876,0.868535,0.667393

,hparams,mae,rmse,spearman,r2_score
270915,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.304756,17.794544,0.875970,0.618990
270906,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.304756,17.794544,0.875970,0.618990
270924,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.304756,17.794544,0.875970,0.618990
270913,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.309068,17.753112,0.875819,0.620763
270904,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.309068,17.753112,0.875819,0.620763

,hparams,mae,rmse,spearman,r2_score
270010,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.829792,16.576679,0.866679,0.669359
270009,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.848839,16.577123,0.868501,0.669341
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.783965,16.597884,0.868456,0.668512
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.809545,16.622568,0.868298,0.667525
270007,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",7.808299,16.625876,0.868535,0.667393

In [5]:
index_opti = 270008
hparams_opti = df_results.loc[index_opti]["hparams"]
hparams_opti.pop("n_jobs")
hparams_opti

{'max_depth': 10,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 500,
 'random_state': 42}

In [6]:
path_hparams_opti = "hparams_opti.json"
df_hparams_opti = pd.DataFrame.from_dict(hparams_opti, orient="index")
if not Path(path_hparams_opti).exists():
    df_hparams_opti.to_json(path_hparams_opti)

pd.read_json(path_hparams_opti).to_dict()[0]

{'max_depth': 10.0,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 500.0,
 'random_state': 42.0}