In [1]:
from pathlib import Path

import pandas as pd

In [2]:
df_results = pd.DataFrame()
for i in range(40):
    path_results = f"{i}_results_gdsearch.json.gz"
    df_results = pd.concat(
        [df_results, pd.read_json(path_results, orient="index")], axis=0
    )
print(df_results.shape)
display(df_results.head())

(360000, 5)

,hparams,mae,rmse,spearman,r2_score
0,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.421218,17.910051,0.726503,0.559647
1,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.330282,17.792763,0.724323,0.565396
2,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.295802,17.701812,0.725978,0.569827
3,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.311310,17.725617,0.729286,0.568670
4,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",9.283316,17.675841,0.731126,0.571089

In [3]:
for metric, ascending in zip(
    ["mae", "rmse", "spearman", "r2_score"], [True, True, False, False]
):
    display(df_results.sort_values(by=metric, ascending=ascending).iloc[:5])

,hparams,mae,rmse,spearman,r2_score
270001,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.346365,13.203587,0.819547,0.760673
270004,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.362934,13.287060,0.821247,0.757638
270000,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.380520,13.169552,0.816147,0.761906
270002,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.383555,13.316795,0.821937,0.756552
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.383985,13.359395,0.822710,0.754992

,hparams,mae,rmse,spearman,r2_score
270000,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.380520,13.169552,0.816147,0.761906
270001,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.346365,13.203587,0.819547,0.760673
270004,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.362934,13.287060,0.821247,0.757638
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.386714,13.299512,0.823312,0.757183
270002,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.383555,13.316795,0.821937,0.756552

,hparams,mae,rmse,spearman,r2_score
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.431726,13.465287,0.824922,0.751092
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.386714,13.299512,0.823312,0.757183
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.383985,13.359395,0.822710,0.754992
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.437356,13.455856,0.822525,0.751441
270002,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.383555,13.316795,0.821937,0.756552

,hparams,mae,rmse,spearman,r2_score
270000,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.380520,13.169552,0.816147,0.761906
270001,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.346365,13.203587,0.819547,0.760673
270004,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.362934,13.287060,0.821247,0.757638
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.386714,13.299512,0.823312,0.757183
270002,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",6.383555,13.316795,0.821937,0.756552

In [4]:
index_opti = 270001
hparams_opti = df_results.loc[index_opti]["hparams"]
hparams_opti.pop("n_jobs")
hparams_opti

{'max_depth': 10,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 150,
 'random_state': 42}

In [5]:
path_hparams_opti = "hparams_opti.json"
df_hparams_opti = pd.DataFrame.from_dict(hparams_opti, orient="index")
if not Path(path_hparams_opti).exists():
    df_hparams_opti.to_json(path_hparams_opti)

pd.read_json(path_hparams_opti).to_dict()[0]

{'max_depth': 10.0,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 150.0,
 'random_state': 42.0}