In [2]:
from pathlib import Path

import pandas as pd

In [3]:
df_results = pd.DataFrame()
for i in range(40):
    path_results = f"{i}_results_gdsearch.json.gz"
    df_results = pd.concat(
        [df_results, pd.read_json(path_results, orient="index")], axis=0
    )
print(df_results.shape)
display(df_results.head())

(360000, 5)

,hparams,mae,rmse,spearman,r2_score
0,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.081371,18.398773,0.782714,0.602470
1,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.062763,18.408698,0.783715,0.602041
2,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.039850,18.410640,0.785571,0.601957
3,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.049008,18.408415,0.786514,0.602054
4,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.030182,18.390022,0.786363,0.602848

In [4]:
for metric, ascending in zip(
    ["mae", "rmse", "spearman", "r2_score"], [True, True, False, False]
):
    display(df_results.sort_values(by=metric, ascending=ascending).iloc[:5])

,hparams,mae,rmse,spearman,r2_score
270007,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.778265,16.687755,0.823314,0.672970
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.788523,16.700722,0.823469,0.672462
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.798076,16.720234,0.823188,0.671696
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.802350,16.728756,0.823246,0.671361
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.824837,16.762333,0.825637,0.670040

,hparams,mae,rmse,spearman,r2_score
270007,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.778265,16.687755,0.823314,0.672970
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.788523,16.700722,0.823469,0.672462
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.798076,16.720234,0.823188,0.671696
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.802350,16.728756,0.823246,0.671361
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.824837,16.762333,0.825637,0.670040

,hparams,mae,rmse,spearman,r2_score
270912,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.976132,17.700412,0.840658,0.632076
270903,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.976132,17.700412,0.840658,0.632076
270921,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.976132,17.700412,0.840658,0.632076
270924,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.958469,17.616794,0.840591,0.635544
270906,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.958469,17.616794,0.840591,0.635544

,hparams,mae,rmse,spearman,r2_score
270007,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.778265,16.687755,0.823314,0.672970
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.788523,16.700722,0.823469,0.672462
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.798076,16.720234,0.823188,0.671696
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.802350,16.728756,0.823246,0.671361
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.824837,16.762333,0.825637,0.670040

In [5]:
index_opti = 270007
hparams_opti = df_results.loc[index_opti]["hparams"]
hparams_opti.pop("n_jobs")
hparams_opti

{'max_depth': 10,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 450,
 'random_state': 42}

In [6]:
path_hparams_opti = "hparams_opti.json"
df_hparams_opti = pd.DataFrame.from_dict(hparams_opti, orient="index")
if not Path(path_hparams_opti).exists():
    df_hparams_opti.to_json(path_hparams_opti)

pd.read_json(path_hparams_opti).to_dict()[0]

{'max_depth': 10.0,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 450.0,
 'random_state': 42.0}