In [2]:
from pathlib import Path

import pandas as pd

In [3]:
df_results = pd.DataFrame()
for i in range(40):
    path_results = f"{i}_results_gdsearch.json.gz"
    df_results = pd.concat(
        [df_results, pd.read_json(path_results, orient="index")], axis=0
    )
print(df_results.shape)
display(df_results.head())

(360000, 5)

,hparams,mae,rmse,spearman,r2_score
0,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.842495,19.313153,0.764190,0.494451
1,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.750113,19.037530,0.765100,0.508778
2,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.693533,18.921411,0.766826,0.514752
3,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.726416,18.992334,0.767730,0.511108
4,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.764290,19.042447,0.768252,0.508524

In [4]:
for metric, ascending in zip(
    ["mae", "rmse", "spearman", "r2_score"], [True, True, False, False]
):
    display(df_results.sort_values(by=metric, ascending=ascending).iloc[:5])

,hparams,mae,rmse,spearman,r2_score
270932,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.746992,19.069554,0.813045,0.507124
270935,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.753109,19.011430,0.813874,0.510124
270934,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.770694,19.084457,0.814753,0.506353
270933,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.773841,19.139412,0.815029,0.503506
270931,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.781978,19.102892,0.812209,0.505399

,hparams,mae,rmse,spearman,r2_score
272792,"{'max_depth': 10, 'min_samples_leaf': 0.015097...",10.225367,18.662131,0.789450,0.527960
271873,"{'max_depth': 10, 'min_samples_leaf': 0.010098...",10.127004,18.698183,0.799410,0.526134
90036,"{'max_depth': 6, 'min_samples_leaf': 0.0001, '...",10.321125,18.704533,0.778243,0.525812
181854,"{'max_depth': 8, 'min_samples_leaf': 0.010098,...",10.027359,18.717677,0.802427,0.525146
272790,"{'max_depth': 10, 'min_samples_leaf': 0.015097...",10.242929,18.720218,0.787539,0.525017

,hparams,mae,rmse,spearman,r2_score
270902,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.840170,19.196609,0.818624,0.500534
270911,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.840170,19.196609,0.818624,0.500534
270920,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.840170,19.196609,0.818624,0.500534
270921,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.853526,19.232184,0.816946,0.498681
270903,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.853526,19.232184,0.816946,0.498681

,hparams,mae,rmse,spearman,r2_score
272792,"{'max_depth': 10, 'min_samples_leaf': 0.015097...",10.225367,18.662131,0.789450,0.527960
271873,"{'max_depth': 10, 'min_samples_leaf': 0.010098...",10.127004,18.698183,0.799410,0.526134
90036,"{'max_depth': 6, 'min_samples_leaf': 0.0001, '...",10.321125,18.704533,0.778243,0.525812
181854,"{'max_depth': 8, 'min_samples_leaf': 0.010098,...",10.027359,18.717677,0.802427,0.525146
272790,"{'max_depth': 10, 'min_samples_leaf': 0.015097...",10.242929,18.720218,0.787539,0.525017

In [5]:
index_opti = 181854
hparams_opti = df_results.loc[index_opti]["hparams"]
hparams_opti.pop("n_jobs")
hparams_opti

{'max_depth': 8,
 'min_samples_leaf': 0.010098,
 'min_samples_split': 0.030094,
 'n_estimators': 100,
 'random_state': 42}

In [6]:
path_hparams_opti = "hparams_opti.json"
df_hparams_opti = pd.DataFrame.from_dict(hparams_opti, orient="index")
if not Path(path_hparams_opti).exists():
    df_hparams_opti.to_json(path_hparams_opti)

pd.read_json(path_hparams_opti).to_dict()[0]

{'max_depth': 8.0,
 'min_samples_leaf': 0.010098,
 'min_samples_split': 0.030094,
 'n_estimators': 100.0,
 'random_state': 42.0}