In [1]:
from pathlib import Path

import pandas as pd

In [2]:
df_results = pd.DataFrame()
for i in range(40):
    path_results = f"{i}_results_gdsearch.json.gz"
    df_results = pd.concat(
        [df_results, pd.read_json(path_results, orient="index")], axis=0
    )
print(df_results.shape)
display(df_results.head())

(195000, 5)

,hparams,mae,rmse,spearman,r2_score
0,"{'learning_rate': 0.05, 'max_depth': 2, 'min_c...",8.060401,15.459756,0.71972,0.671895
1,"{'learning_rate': 0.05, 'max_depth': 2, 'min_c...",8.060401,15.459756,0.71972,0.671895
2,"{'learning_rate': 0.05, 'max_depth': 2, 'min_c...",8.060401,15.459756,0.71972,0.671895
3,"{'learning_rate': 0.05, 'max_depth': 2, 'min_c...",8.060401,15.459756,0.71972,0.671895
4,"{'learning_rate': 0.05, 'max_depth': 2, 'min_c...",8.060401,15.459756,0.71972,0.671895

In [3]:
for metric, ascending in zip(
    ["mae", "rmse", "spearman", "r2_score"], [True, True, False, False]
):
    display(df_results.sort_values(by=metric, ascending=ascending).iloc[:5])

,hparams,mae,rmse,spearman,r2_score
52082,"{'learning_rate': 0.16818181818181802, 'max_de...",5.546677,11.936132,0.822470,0.804415
149974,"{'learning_rate': 0.395454545454545, 'max_dept...",5.597808,11.632796,0.796762,0.814230
149779,"{'learning_rate': 0.395454545454545, 'max_dept...",5.598970,11.529538,0.770980,0.817513
149389,"{'learning_rate': 0.395454545454545, 'max_dept...",5.607275,11.596721,0.785788,0.815380
52277,"{'learning_rate': 0.16818181818181802, 'max_de...",5.608051,11.971344,0.807902,0.803260

,hparams,mae,rmse,spearman,r2_score
147692,"{'learning_rate': 0.39090909090909004, 'max_de...",5.970876,11.007386,0.723699,0.833668
84843,"{'learning_rate': 0.245454545454545, 'max_dept...",5.641740,11.040411,0.810876,0.832668
129210,"{'learning_rate': 0.35000000000000003, 'max_de...",6.235985,11.053198,0.724989,0.832281
156856,"{'learning_rate': 0.413636363636363, 'max_dept...",6.300551,11.127509,0.717045,0.830018
148082,"{'learning_rate': 0.39090909090909004, 'max_de...",6.047725,11.139291,0.725309,0.829658

,hparams,mae,rmse,spearman,r2_score
67503,"{'learning_rate': 0.204545454545454, 'max_dept...",7.000401,14.332315,0.853708,0.718006
71998,"{'learning_rate': 0.213636363636363, 'max_dept...",6.322712,12.814711,0.853161,0.774563
125583,"{'learning_rate': 0.34090909090909005, 'max_de...",7.101320,15.936010,0.852645,0.651369
112917,"{'learning_rate': 0.309090909090909, 'max_dept...",6.964487,15.423527,0.851232,0.673431
120768,"{'learning_rate': 0.32727272727272705, 'max_de...",7.749030,16.476448,0.849370,0.627321

,hparams,mae,rmse,spearman,r2_score
147692,"{'learning_rate': 0.39090909090909004, 'max_de...",5.970876,11.007386,0.723699,0.833668
84843,"{'learning_rate': 0.245454545454545, 'max_dept...",5.641740,11.040411,0.810876,0.832668
129210,"{'learning_rate': 0.35000000000000003, 'max_de...",6.235985,11.053198,0.724989,0.832281
156856,"{'learning_rate': 0.413636363636363, 'max_dept...",6.300551,11.127509,0.717045,0.830018
148082,"{'learning_rate': 0.39090909090909004, 'max_de...",6.047725,11.139291,0.725309,0.829658

In [4]:
index_opti = 71998
hparams_opti = df_results.loc[index_opti]["hparams"]
hparams_opti.pop("n_jobs")
hparams_opti

{'learning_rate': 0.213636363636363,
 'max_depth': 20,
 'min_child_samples': 10,
 'num_leaves': 140,
 'random_state': 42}

In [5]:
path_hparams_opti = "hparams_opti.json"
df_hparams_opti = pd.DataFrame.from_dict(hparams_opti, orient="index")
if not Path(path_hparams_opti).exists():
    df_hparams_opti.to_json(path_hparams_opti)

pd.read_json(path_hparams_opti).to_dict()[0]

{'learning_rate': 0.21363636360000002,
 'max_depth': 20.0,
 'min_child_samples': 10.0,
 'num_leaves': 140.0,
 'random_state': 42.0}