In [2]:
from pathlib import Path

import pandas as pd

In [3]:
df_results = pd.DataFrame()
for i in range(40):
    path_results = f"{i}_results_gdsearch.json.gz"
    df_results = pd.concat(
        [df_results, pd.read_json(path_results, orient="index")], axis=0
    )
print(df_results.shape)
display(df_results.head())

(360000, 5)

,hparams,mae,rmse,spearman,r2_score
0,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.546311,18.980143,0.753680,0.576951
1,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.569550,19.068363,0.755727,0.573009
2,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.534005,19.023589,0.756840,0.575012
3,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.555522,19.084042,0.755316,0.572307
4,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.540159,19.020025,0.757618,0.575171

In [4]:
for metric, ascending in zip(
    ["mae", "rmse", "spearman", "r2_score"], [True, True, False, False]
):
    display(df_results.sort_values(by=metric, ascending=ascending).iloc[:5])

,hparams,mae,rmse,spearman,r2_score
270004,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.193894,16.957605,0.814953,0.662308
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.197509,16.945895,0.815919,0.662774
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.204743,16.946513,0.815537,0.662750
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.207363,16.994249,0.817180,0.660847
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.208832,17.008515,0.815401,0.660277

,hparams,mae,rmse,spearman,r2_score
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.197509,16.945895,0.815919,0.662774
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.204743,16.946513,0.815537,0.662750
270004,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.193894,16.957605,0.814953,0.662308
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.207363,16.994249,0.817180,0.660847
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.208832,17.008515,0.815401,0.660277

,hparams,mae,rmse,spearman,r2_score
270906,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.939436,17.98911,0.823055,0.619976
270915,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.939436,17.98911,0.823055,0.619976
270924,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.939436,17.98911,0.823055,0.619976
270910,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.960029,18.09662,0.822892,0.615420
270919,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",8.960029,18.09662,0.822892,0.615420

,hparams,mae,rmse,spearman,r2_score
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.197509,16.945895,0.815919,0.662774
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.204743,16.946513,0.815537,0.662750
270004,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.193894,16.957605,0.814953,0.662308
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.207363,16.994249,0.817180,0.660847
270003,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.208832,17.008515,0.815401,0.660277

In [5]:
index_opti = 270006
hparams_opti = df_results.loc[index_opti]["hparams"]
hparams_opti.pop("n_jobs")
hparams_opti

{'max_depth': 10,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 400,
 'random_state': 42}

In [6]:
path_hparams_opti = "hparams_opti.json"
df_hparams_opti = pd.DataFrame.from_dict(hparams_opti, orient="index")
if not Path(path_hparams_opti).exists():
    df_hparams_opti.to_json(path_hparams_opti)

pd.read_json(path_hparams_opti).to_dict()[0]

{'max_depth': 10.0,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 400.0,
 'random_state': 42.0}