In [2]:
from pathlib import Path

import pandas as pd

In [3]:
df_results = pd.DataFrame()
for i in range(40):
    path_results = f"{i}_results_gdsearch.json.gz"
    df_results = pd.concat(
        [df_results, pd.read_json(path_results, orient="index")], axis=0
    )
print(df_results.shape)
display(df_results.head())

(360000, 5)

,hparams,mae,rmse,spearman,r2_score
0,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.387298,18.446285,0.763764,0.538816
1,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.358007,18.442013,0.763721,0.539029
2,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.341153,18.504365,0.764064,0.535907
3,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.346316,18.508845,0.765563,0.535682
4,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.348982,18.507664,0.765836,0.535742

In [4]:
for metric, ascending in zip(
    ["mae", "rmse", "spearman", "r2_score"], [True, True, False, False]
):
    display(df_results.sort_values(by=metric, ascending=ascending).iloc[:5])

,hparams,mae,rmse,spearman,r2_score
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.375753,18.273828,0.798937,0.547399
270023,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.382702,18.000809,0.798341,0.560822
270021,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.390897,17.963144,0.799355,0.562658
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.395575,18.441396,0.798900,0.539060
270026,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.397365,18.082755,0.799803,0.556814

,hparams,mae,rmse,spearman,r2_score
270021,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.390897,17.963144,0.799355,0.562658
270023,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.382702,18.000809,0.798341,0.560822
270022,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.405609,18.004339,0.798531,0.560650
90036,"{'max_depth': 6, 'min_samples_leaf': 0.0001, '...",10.013795,18.058839,0.774759,0.557986
270024,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.409249,18.074406,0.798323,0.557223

,hparams,mae,rmse,spearman,r2_score
270910,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.633704,19.069606,0.825210,0.507121
270901,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.633704,19.069606,0.825210,0.507121
270919,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.633704,19.069606,0.825210,0.507121
270911,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.591151,19.080222,0.824233,0.506572
270902,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.591151,19.080222,0.824233,0.506572

,hparams,mae,rmse,spearman,r2_score
270021,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.390897,17.963144,0.799355,0.562658
270023,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.382702,18.000809,0.798341,0.560822
270022,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.405609,18.004339,0.798531,0.560650
90036,"{'max_depth': 6, 'min_samples_leaf': 0.0001, '...",10.013795,18.058839,0.774759,0.557986
270024,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",9.409249,18.074406,0.798323,0.557223

In [5]:
index_opti = 270023
hparams_opti = df_results.loc[index_opti]["hparams"]
hparams_opti.pop("n_jobs")
hparams_opti

{'max_depth': 10,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.010098,
 'n_estimators': 350,
 'random_state': 42}

In [6]:
path_hparams_opti = "hparams_opti.json"
df_hparams_opti = pd.DataFrame.from_dict(hparams_opti, orient="index")
if not Path(path_hparams_opti).exists():
    df_hparams_opti.to_json(path_hparams_opti)

pd.read_json(path_hparams_opti).to_dict()[0]

{'max_depth': 10.0,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.010098,
 'n_estimators': 350.0,
 'random_state': 42.0}