In [2]:
from pathlib import Path

import pandas as pd

In [3]:
df_results = pd.DataFrame()
for i in range(40):
    path_results = f"{i}_results_gdsearch.json.gz"
    df_results = pd.concat(
        [df_results, pd.read_json(path_results, orient="index")], axis=0
    )
print(df_results.shape)
display(df_results.head())

(360000, 5)

,hparams,mae,rmse,spearman,r2_score
0,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.453972,18.622871,0.695892,0.529944
1,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.507142,18.640237,0.696384,0.529067
2,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.493478,18.644403,0.691574,0.528856
3,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.497237,18.680040,0.695865,0.527053
4,"{'max_depth': 4, 'min_samples_leaf': 0.0001, '...",10.454783,18.610931,0.697598,0.530546

In [4]:
for metric, ascending in zip(
    ["mae", "rmse", "spearman", "r2_score"], [True, True, False, False]
):
    display(df_results.sort_values(by=metric, ascending=ascending).iloc[:5])

,hparams,mae,rmse,spearman,r2_score
270000,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.275409,16.485789,0.784514,0.631637
270001,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.281275,16.559824,0.785012,0.628321
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.370117,16.711713,0.791158,0.621472
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.373308,16.706413,0.791797,0.621712
270007,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.385497,16.747698,0.792055,0.619840

,hparams,mae,rmse,spearman,r2_score
270000,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.275409,16.485789,0.784514,0.631637
270001,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.281275,16.559824,0.785012,0.628321
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.373308,16.706413,0.791797,0.621712
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.370117,16.711713,0.791158,0.621472
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.391373,16.732831,0.791754,0.620514

,hparams,mae,rmse,spearman,r2_score
270900,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.512811,18.819279,0.805814,0.519976
270909,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.512811,18.819279,0.805814,0.519976
270918,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.512811,18.819279,0.805814,0.519976
270913,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.494473,18.815592,0.802895,0.520164
270922,"{'max_depth': 10, 'min_samples_leaf': 0.005098...",9.494473,18.815592,0.802895,0.520164

,hparams,mae,rmse,spearman,r2_score
270000,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.275409,16.485789,0.784514,0.631637
270001,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.281275,16.559824,0.785012,0.628321
270006,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.373308,16.706413,0.791797,0.621712
270005,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.370117,16.711713,0.791158,0.621472
270008,"{'max_depth': 10, 'min_samples_leaf': 0.0001, ...",8.391373,16.732831,0.791754,0.620514

In [5]:
index_opti = 270000
hparams_opti = df_results.loc[index_opti]["hparams"]
hparams_opti.pop("n_jobs")
hparams_opti

{'max_depth': 10,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 100,
 'random_state': 42}

In [6]:
path_hparams_opti = "hparams_opti.json"
df_hparams_opti = pd.DataFrame.from_dict(hparams_opti, orient="index")
if not Path(path_hparams_opti).exists():
    df_hparams_opti.to_json(path_hparams_opti)

pd.read_json(path_hparams_opti).to_dict()[0]

{'max_depth': 10.0,
 'min_samples_leaf': 0.0001,
 'min_samples_split': 0.0001,
 'n_estimators': 100.0,
 'random_state': 42.0}